### ISSUE TITLE
reflection necessary because of http PATCH with Object?

### ISSUE THREAD

**Issue by 886419** [Lars-v-Delft/BilliardsAPI#6]
https://github.com/Lars-v-Delft/BilliardsAPI/blob/0c900439548ff10eb3a1e9cfa3588c29c03d2083/src/main/java/com/biljartline/billiardsapi/competition/CompetitionController.java#L66C37-L66C37

1. reflectie is een beetje last-resort. Probeer het te vermijden, de compiler kan je bijv. niet goed helpen met type-safety.
2. idem vermijd gebruik van Object, zeker in een API. Alles kan met Object, dat programmeert als een trein, compileert altijd, maar errors kom je pas runtime tegen, en dat is duur.
3. (of is dat echt een http PATCH design-pattern?)

**Comment by Lars-v-Delft** [comment]
Bovenstaande 3 issues zijn behandeld, zie https://github.com/Lars-v-Delft/BilliardsAPI/blob/f0ca88fe40348156129394b7d1681ce2075885fa/src/main/java/com/biljartline/billiardsapi/competition/CompetitionController.java#L67
